name: Build Python wheels

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    # Check all PR

permissions:
  pull-requests: write

jobs:
  merge-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Re-upload a single wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheels/*

      - uses: PicoCentauri/comment-artifact@v1
        with:
          name: wheels
          text: ⚙️ Download wheels for this pull-request
