name: Build Python wheels

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    # Check all PR

permissions:
  pull-requests: write

jobs:
  merge-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Re-upload a single wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheels/*
      - uses: PicoCentauri/comment-artifact@main
        with:
          name: wheels
          description: ⚙️ Download the wheels for this pull-request
